### ISSUE TITLE
Hello! I am trying to run the workflow. I must said I am not used to work within python envs. I have tried running snakemake from different sources but none is working. Maybe you could understand what is happening: Thank you in advance!

### ISSUE THREAD

**Issue by somnya** [mrvollger/StainedGlass#10]
Mitchell R Vollger, Peter Kerpedjiev, Adam M Phillippy, Evan E Eichler.
            "StainedGlass: Interactive visualization of massive tandem repeat structures with identity heatmaps"
            Bioinformatics, 2022; https://doi.org/10.1093/bioinformatics/btac018

[INFO] The sequence will be split into 4 batches.
Building DAG of jobs...
Removing incomplete Conda environment workflow/envs/env.yaml...
Creating conda environment workflow/envs/env.yaml...
Downloading and installing remote packages.
CreateCondaEnvironmentException:
Could not create conda environment from /mnt/c/Users/52722/Desktop/Agave/genome/tes/vitral/StainedGlass/workflow/envs/env.yaml:
Preparing transaction: ...working... done
Verifying transaction: ...working... failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/mnt/c/Users/52722/Desktop/anaconda/lib/python3.9/site-packages/conda/exceptions.py", line 1080, in __call__
        return func(*args, **kwargs)
      File "/mnt/c/Users/52722/Desktop/anaconda/lib/python3.9/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/mnt/c/Users/52722/Desktop/anaconda/lib/python3.9/site-packages/conda_env/cli/main_create.py", line 141, in execute
        result[installer_type] = installer.install(prefix, pkg_specs, args, env)
      File "/mnt/c/Users/52722/Desktop/anaconda/lib/python3.9/site-packages/mamba/mamba_env.py", line 95, in mamba_install
        conda_transaction.execute()
      File "/mnt/c/Users/52722/Desktop/anaconda/lib/python3.9/site-packages/conda/core/link.py", line 245, in execute
        self.verify()
      File "/mnt/c/Users/52722/Desktop/anaconda/lib/python3.9/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/mnt/c/Users/52722/Desktop/anaconda/lib/python3.9/site-packages/conda/core/link.py", line 232, in verify
        exceptions = self._verify(self.prefix_setups, self.prefix_action_groups)
      File "/mnt/c/Users/52722/Desktop/anaconda/lib/python3.9/site-packages/conda/core/link.py", line 591, in _verify
        for exc in self.verify_executor.map(UnlinkLinkTransaction._verify_individual_level,
      File "/mnt/c/Users/52722/Desktop/anaconda/lib/python3.9/site-packages/conda/common/io.py", line 525, in map
        yield func(thing)
      File "/mnt/c/Users/52722/Desktop/anaconda/lib/python3.9/site-packages/conda/core/link.py", line 412, in _verify_individual_level
        error_result = axn.verify()
      File "/mnt/c/Users/52722/Desktop/anaconda/lib/python3.9/site-packages/conda/core/path_actions.py", line 323, in verify
        source_size_in_bytes = getsize(self.source_full_path)
      File "/mnt/c/Users/52722/Desktop/anaconda/lib/python3.9/genericpath.py", line 50, in getsize
        return os.stat(filename).st_size
    OSError: [Errno 40] Too many levels of symbolic links: '/mnt/c/Users/52722/Desktop/anaconda/pkgs/ncurses-6.3-h9c3ff4c_0/share/terminfo/N/NCR260VT300WPP'

`$ /mnt/c/Users/52722/Desktop/anaconda/bin/mamba create --quiet --file /mnt/c/Users/52722/Desktop/Agave/genome/tes/vitral/StainedGlass/.snakemake/conda/11a78e4d8d4eb3e16355f0acfb4fede7.yaml --prefix /mnt/c/Users/52722/Desktop/Agave/genome/tes/vitral/StainedGlass/.snakemake/conda/11a78e4d8d4eb3e16355f0acfb4fede7`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/mnt/c/Users/52722/Desktop/anaconda/bin/conda
             CONDA_PREFIX=/mnt/c/Users/52722/Desktop/anaconda
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/mnt/c/Users/52722/Desktop/anaconda/bin/python
               CONDA_ROOT=/mnt/c/Users/52722/Desktop/anaconda
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                     PATH=/mnt/c/Users/52722/Desktop/anaconda/bin:/mnt/c/Users/52722/Desktop/ana
                          conda/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin
                          :/bin:/usr/games:/usr/local/games:/mnt/c/Program Files (x86)/Common Fi
                          les/Oracle/Java/javapath:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c
                          /WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0:
                          /mnt/c/WINDOWS/System32/OpenSSH:/mnt/d/Program
                          Files/PuTTY:/mnt/d/Program Files/TreeViewer:/mnt/d/Program files/Git/c
                          md:/mnt/d/blast-2.11.0+/bin:/mnt/c/Users/52722/AppData/Local/Microsoft
                          /WindowsApps:/mnt/d/Inkscape/bin:/snap/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /mnt/c/Users/52722/Desktop/anaconda
            shell level : 1
       user config file : /home/somnya_ollin/.condarc
 populated config files :
          conda version : 4.11.0
    conda-build version : 3.21.5
         python version : 3.9.7.final.0
       virtual packages : __linux=4.4.0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /mnt/c/Users/52722/Desktop/anaconda  (writable)
      conda av data dir : /mnt/c/Users/52722/Desktop/anaconda/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /mnt/c/Users/52722/Desktop/anaconda/pkgs
                          /home/somnya_ollin/.conda/pkgs
       envs directories : /mnt/c/Users/52722/Desktop/anaconda/envs
                          /home/somnya_ollin/.conda/envs
               platform : linux-64
             user-agent : conda/4.11.0 requests/2.26.0 CPython/3.9.7 Linux/4.4.0-19041-Microsoft ubuntu/20.04 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.

**Comment by mrvollger** [comment]
Hi there, 

This looks like an internal snakemake error. 

Could you share the version of `snakemake` you are using as well as which `mamba` version. 

Thanks.

**Comment by mrvollger** [comment]
Closing because of inactivity.
