### ISSUE TITLE
issues with env.yaml - dropbox dependency

### ISSUE THREAD

**Issue by laramiemckenna** [mrvollger/StainedGlass#19]
Hello! I've enjoyed using this tool. Recently, I came across a dependency issue that I have not encountered in the past, and I am trying to figure out how to fix it. Even after individually installing each item in the env.yaml file, I keep getting this error although Dropbox is already installed within this environment. Do you have any recommendations for troubleshooting this? 

```
^[[92m^[[1mThanks for using StainedGlass and please remember to cite the tool!^[[0m^[[0m
    ^[[36mMitchell R Vollger, Peter Kerpedjiev, Adam M Phillippy, Evan E Eichler.
            "StainedGlass: Interactive visualization of massive tandem repeat structures with identity heatmaps"
            Bioinformatics, 2022; https://doi.org/10.1093/bioinformatics/btac018^[[0m

Config file config/config.yaml is extended by additional config specified via the command line.
[INFO] The sequence will be split into 4 batches.
Building DAG of jobs...
Creating conda environment workflow/envs/env.yaml...
Downloading and installing remote packages.
CreateCondaEnvironmentException:
Could not create conda environment from /cluster/home/lasmith/misc_analyses/ambo_stained_glass/Hap2/StainedGlass/workflow/envs/env.yaml:
Command:
mamba env create --quiet --file "/cluster/home/lasmith/misc_analyses/ambo_stained_glass/Hap2/StainedGlass/.snakemake/conda/8827facc6da39e2c8300f5a40c61015a.yaml" $
Output:
Could not solve for environment specs
Encountered problems while solving:
  - package snakemake-7.11.0-hdfd78af_0 requires dropbox >=7.2.1, but none of the providers can be installed

The environment can't be solved, aborting the operation
```

**Comment by mrvollger** [comment]
Hi there!

Glad it's been useful and working until now!

I remember seeing this Dropbox error before while using someone else's yaml but I cannot remember how I solved it...

While I track that down I think I may have a solution for you. I don't think snakemake and snakefmt are actually needed in env.yaml. At least on my machine that don't seem to be needed. Can you try removing these two lines:  
  - snakemake>=7.8
  - snakefmt
And if it works and your results look as expected I'll remove these unneeded dependencies. 

Cheers,
Mitchell

**Comment by laramiemckenna** [comment]
Thank you for the incredibly quick response! I removed those lines and re-ran, but this produced a new error. I'll share it here and also work on trouble-shooting it on my end! Please let me know if there's any other information or files I can provide. 

```
Config file config/config.yaml is extended by additional config specified via the command line.
[INFO] The sequence will be split into 4 batches.
Building DAG of jobs...
Creating conda environment workflow/envs/env.yaml...
Downloading and installing remote packages.
Environment for /cluster/home/lasmith/misc_analyses/ambo_stained_glass/Hap2/StainedGlass/workflow/envs/env.yaml created (location: .snakemake/conda/91b512244a085e20527fbe4621c70a26)
Using shell: /usr/bin/bash
Provided cluster nodes: 1
Traceback (most recent call last):
  File "/cluster/home/lasmith/mambaforge/envs/snakemake/lib/python3.9/site-packages/snakemake/__init__.py", line 730, in snakemake
    success = workflow.execute(
  File "/cluster/home/lasmith/mambaforge/envs/snakemake/lib/python3.9/site-packages/snakemake/workflow.py", line 1026, in execute
    logger.run_info("\n".join(dag.stats()))
  File "/cluster/home/lasmith/mambaforge/envs/snakemake/lib/python3.9/site-packages/snakemake/dag.py", line 2398, in stats
    yield tabulate(rows, headers="keys")
  File "/cluster/home/lasmith/mambaforge/envs/snakemake/lib/python3.9/site-packages/tabulate/__init__.py", line 2048, in tabulate
    list_of_lists, headers = _normalize_tabular_data(
  File "/cluster/home/lasmith/mambaforge/envs/snakemake/lib/python3.9/site-packages/tabulate/__init__.py", line 1471, in _normalize_tabular_data
    rows = list(map(lambda r: r if _is_separating_line(r) else list(r), rows))
  File "/cluster/home/lasmith/mambaforge/envs/snakemake/lib/python3.9/site-packages/tabulate/__init__.py", line 1471, in <lambda>
    rows = list(map(lambda r: r if _is_separating_line(r) else list(r), rows))
  File "/cluster/home/lasmith/mambaforge/envs/snakemake/lib/python3.9/site-packages/tabulate/__init__.py", line 107, in _is_separating_line
    (len(row) >= 1 and row[0] == SEPARATING_LINE)
  File "/cluster/home/lasmith/mambaforge/envs/snakemake/lib/python3.9/site-packages/snakemake/rules.py", line 1222, in __eq__
    return self.name == other.name and self.output == other.output
AttributeError: 'str' object has no attribute 'name'
```

**Comment by laramiemckenna** [comment]
**Update:** I updated snakemake to its current version (v7.19.1). It looks like I had tried to downgrade it to v7.11 to troubleshoot the dropbox error. So, with that change and those two lines removed from env.yaml, everything works flawlessly! Thank you so much for your help.
