### ISSUE TITLE
Running error

### ISSUE THREAD

**Issue by jiadong324** [mrvollger/StainedGlass#27]
Dear author,

Conda environment is created via ```conda create -n StainedGlass -c conda-forge -c bioconda snakemake```

Then, I run the command under the conda environment: 
```
snakemake --use-conda --cores 24 --config sample=D-B fasta=ptg000076l.fa temp=./myout
```

The error is shown below:

```
Building DAG of jobs...
Creating conda environment workflow/envs/env.yaml...
Downloading and installing remote packages.
CreateCondaEnvironmentException:
Could not create conda environment from /data/home/jdlin/Biotools/StainedGlass/workflow/envs/env.yaml:
Command:
mamba env create --quiet --file "/data/home/jdlin/Biotools/StainedGlass/.snakemake/conda/aa1c2f2349483ce17474f426bb47cf53_.yaml" --prefix "/data/home/jdlin/Biotools/StainedGlass/.snakemake/conda/aa1c2f2349483ce17474f426bb47cf53_"
Output:

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/data/home/jdlin/miniconda3/envs/StainedGlass/lib/python3.11/site-packages/conda/exception_handler.py", line 16, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/data/home/jdlin/miniconda3/envs/StainedGlass/lib/python3.11/site-packages/conda_env/cli/main.py", line 49, in do_call
        exit_code = getattr(module, func_name)(args, parser)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/home/jdlin/miniconda3/envs/StainedGlass/lib/python3.11/site-packages/conda/notices/core.py", line 123, in wrapper
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/data/home/jdlin/miniconda3/envs/StainedGlass/lib/python3.11/site-packages/conda_env/cli/main_create.py", line 163, in execute
        result[installer_type] = installer.install(
                                 ^^^^^^^^^^^^^^^^^^
      File "/data/home/jdlin/miniconda3/envs/StainedGlass/lib/python3.11/site-packages/mamba/mamba_env.py", line 55, in mamba_install
        index = load_channels(pool, channel_urls, repos, prepend=False)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/home/jdlin/miniconda3/envs/StainedGlass/lib/python3.11/site-packages/mamba/utils.py", line 143, in load_channels
        index = get_index(
                ^^^^^^^^^^
      File "/data/home/jdlin/miniconda3/envs/StainedGlass/lib/python3.11/site-packages/mamba/utils.py", line 124, in get_index
        is_downloaded = dlist.download(api.MAMBA_DOWNLOAD_FAILFAST)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    RuntimeError: Download error (6) Couldn't resolve host name [https://conda.anaconda.org/conda-forge/noarch/repodata.json.zst]
    Could not resolve host: conda.anaconda.org

`$ /data/home/jdlin/miniconda3/envs/StainedGlass/bin/mamba create --quiet --file /data/home/jdlin/Biotools/StainedGlass/.snakemake/conda/aa1c2f2349483ce17474f426bb47cf53_.yaml --prefix /data/home/jdlin/Biotools/StainedGlass/.snakemake/conda/aa1c2f2349483ce17474f426bb47cf53_`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=StainedGlass
                CONDA_EXE=/data/home/jdlin/miniconda3/bin/conda
             CONDA_PREFIX=/data/home/jdlin/miniconda3/envs/StainedGlass
           CONDA_PREFIX_1=/data/home/jdlin/miniconda3
           CONDA_PREFIX_2=/data/home/jdlin/miniconda3/envs/dna
    CONDA_PROMPT_MODIFIER=(StainedGlass)
         CONDA_PYTHON_EXE=/data/home/jdlin/miniconda3/bin/python
               CONDA_ROOT=/data/home/jdlin/miniconda3/envs/StainedGlass
              CONDA_SHLVL=3
           CURL_CA_BUNDLE=<not set>
               LD_PRELOAD=<not set>
                     PATH=/data/home/jdlin/.local/bin:/data/home/jdlin/miniconda3/envs/StainedGl
                          ass/bin:/data/home/jdlin/miniconda3/condabin:/var/lib/torque/bin:/var/
                          lib/torque/sbin:/var/lib/torque/bin:/var/lib/torque/sbin:/usr/local/sb
                          in:/usr/local/bin:/usr/sbin:/usr/bin:/opt/ibutils/bin:/var/lib/hwloc/b
                          in:/var/lib/hwloc/sbin:/root/bin:/var/lib/hwloc/bin:/var/lib/hwloc/sbi
                          n:/data/software/bedtools2/bin:/data/software/bedtools2/bin:/data/home
                          /jdlin/.local/bin:/data/home/jdlin/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /data/home/jdlin/miniconda3/envs/StainedGlass
            shell level : 3
       user config file : /data/home/jdlin/.condarc
 populated config files : /data/home/jdlin/.condarc
          conda version : 23.5.2
    conda-build version : not installed
         python version : 3.11.4.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.17=0
                          __linux=3.10.0=0
                          __unix=0=0
       base environment : /data/home/jdlin/miniconda3/envs/StainedGlass  (writable)
      conda av data dir : /data/home/jdlin/miniconda3/envs/StainedGlass/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /data/home/jdlin/miniconda3/envs/StainedGlass/pkgs
                          /data/home/jdlin/.conda/pkgs
       envs directories : /data/home/jdlin/miniconda3/envs/StainedGlass/envs
                          /data/home/jdlin/.conda/envs
               platform : linux-64
             user-agent : conda/23.5.2 requests/2.31.0 CPython/3.11.4 Linux/3.10.0-957.el7.x86_64 centos/7.6.1810 glibc/2.17
                UID:GID : 1025:1025
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

```
It seams that the Snakefile tries to create the environment with ./env.yaml and the error occurs.

**Comment by mrvollger** [comment]
The error leads me to believe that you don’t have internet access. Is that the case?

**Comment by jiadong324** [comment]
I change the internet access and execute the same command under the conda environment.

Here is part of the log file:

```
Could not solve for environment specs
The following packages are incompatible
├─ cooler 0.9.1**  is installable and it requires
│  ├─ h5py >=2.5  with the potential options
│  │  ├─ h5py [2.10.0|2.6.0|...|3.7.0], which can be installed;
│  │  ├─ h5py [2.10.0|3.1.0] would require
│  │  │  └─ python_abi 3.6.* *_cp36m, which can be installed;
│  │  ├─ h5py [2.10.0|3.1.0|3.2.1|3.3.0] would require
│  │  │  └─ python_abi 3.7.* *_cp37m, which can be installed;
│  │  ├─ h5py [2.10.0|3.1.0|3.2.1|3.3.0] would require
│  │  │  └─ python_abi 3.8.* *_cp38, which conflicts with any installable versions previously reported;
│  │  ├─ h5py [2.10.0|3.1.0|3.2.1|3.3.0] would require
│  │  │  └─ python_abi 3.9.* *_cp39, which conflicts with any installable versions previously reported;
│  │  ├─ h5py 2.6.0 would require
│  │  │  └─ hdf5 1.8.15* , which does not exist (perhaps a missing channel);
│  │  ├─ h5py [3.3.0|3.4.0|3.6.0|3.7.0] would require

```

**Comment by mrvollger** [comment]
I think I have finally fixed the environments, can you pull the latest updates and see if it works for you know?

**Comment by jiadong324** [comment]
Thanks for your help, it works! But it seems that I am not able to customize the output directory with ```temp=```.

**Comment by mrvollger** [comment]
Please see snakemake's documentation on how to modify the result directories. There is no temp variable that can be modified as you indicate here.
