### ISSUE TITLE
cooler error

### ISSUE THREAD

**Issue by Gon1976** [mrvollger/StainedGlass#46]
Hi
I solve de env.yaml problem with numpy, but now I have another problem.
This is my env.yaml nbew file
name: python_and_cli_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - numpy>=1.22.4,<2.3.0
  - numba
  - cooler<=0.8.11
  - pandas<=1.5
  - minimap2==2.18
  - bioconda::bedtools
  - bioconda::samtools>=1.14
  - bioconda::htslib>=1.14
  - bioconda::pysam>=0.15.0
  - bioconda::bwa
  - pigz

After delete the olde .snakemake/conda/file.yaml and folder generated in the previous run. I launch again the command:
(snakemake) ggreif@UBM12:~/StainedGlass$ snakemake --cores 24 cooler_density --config window=32 cooler_window=100
Using workflow specific profile workflow/profiles/default for setting default command line arguments.
Thanks for using StainedGlass and please remember to cite the tool!
    Mitchell R Vollger, Peter Kerpedjiev, Adam M Phillippy, Evan E Eichler.
            "StainedGlass: Interactive visualization of massive tandem repeat structures with identity heatmaps"
            Bioinformatics, 2022; https://doi.org/10.1093/bioinformatics/btac018

Config file config/config.yaml is extended by additional config specified via the command line.
[INFO] The sequence will be split into 4 batches.
Assuming unrestricted shared filesystem usage.
Building DAG of jobs...
Your conda installation is not configured to use strict channel priorities. This is however crucial for having robust and correct environments (for details, see https://conda-forge.org/docs/user/tipsandtricks.html). Please consider to configure strict priorities by executing 'conda config --set channel_priority strict'.
**Creating conda environment workflow/envs/env.yaml.**..
Downloading and installing remote packages.
**Environment for /home/ggreif/StainedGlass/workflow/envs/env.yaml created (location: .snakemake/conda/8ce506b402ad6a359d1e19097a8dba54_**) ##Now the numpy version it's ok
Using shell: /usr/bin/bash
Provided cores: 24
Rules claiming more threads will be scaled down.
Job stats:
job                 count
----------------  -------
cooler_density          1
cooler_density_d        1
cooler_zoomify_d        1
total                   3

Select jobs to execute...
Execute 1 jobs...

[Fri May 24 09:44:47 2024]
localrule cooler_density_d:
    input: results/contacts_Dm25_32.gz, /home/ggreif/StainedGlass/TcDm25_H1.fasta.fai
    output: results/Dm25.32.100.density.cool
    log: logs/cooler_density.Dm25.32.100.log
    jobid: 2
    reason: Missing output files: results/Dm25.32.100.density.cool
    wildcards: SM=Dm25, W=32, CW=100
    resources: mem_mb=16096, mem_mib=15351, disk_mb=1000, disk_mib=954, tmpdir=/tmp, runtime=120, mem=64

Activating conda environment: .snakemake/conda/8ce506b402ad6a359d1e19097a8dba54_
/home/ggreif/StainedGlass/.snakemake/conda/8ce506b402ad6a359d1e19097a8dba54_/lib/python3.10/site-packages/cooler/util.py:690: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  columns, dtype=None, index_columns=None, index_names=None, default_dtype=np.object
Traceback (most recent call last):
  File "/home/ggreif/StainedGlass/.snakemake/conda/8ce506b402ad6a359d1e19097a8dba54_/bin/cooler", line 6, in <module>
    from cooler.cli import cli
  File "/home/ggreif/StainedGlass/.snakemake/conda/8ce506b402ad6a359d1e19097a8dba54_/lib/python3.10/site-packages/cooler/__init__.py", line 14, in <module>
    from .api import Cooler, annotate
  File "/home/ggreif/StainedGlass/.snakemake/conda/8ce506b402ad6a359d1e19097a8dba54_/lib/python3.10/site-packages/cooler/api.py", line 22, in <module>
    from .util import parse_cooler_uri, parse_region, open_hdf5, closing_hdf5
  File "/home/ggreif/StainedGlass/.snakemake/conda/8ce506b402ad6a359d1e19097a8dba54_/lib/python3.10/site-packages/cooler/util.py", line 690, in <module>
    columns, dtype=None, index_columns=None, index_names=None, default_dtype=np.object
  File "/home/ggreif/StainedGlass/.snakemake/conda/8ce506b402ad6a359d1e19097a8dba54_/lib/python3.10/site-packages/numpy/__init__.py", line 324, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'object'.
`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'object_'?

Any idea how to solve this?
thanks

**Comment by Gon1976** [comment]
I solved modifying  util.py here:  sed 's/np.object/object/g' .snakemake/conda/8ce506b402ad6a359d1e19097a8dba54_/lib/python3.10/site-packages/cooler/util.py
After change util.py I run with the command:snakemake --cores 24 cooler_density --config window=32 cooler_window=100 --use-conda --rerun-incomplete
and works. I close the issue
